# Generated by Django 5.0.14 on 2026-07-16 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ('sent_at',),
            },
        ),
    ]
