# Generated by Django 5.0.14 on 2026-08-03 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
        ('matches', '0003_matchrequest_match_receiver_status_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_message_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['match', 'sent_at'], name='message_match_sent_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False), models.Q(('client_message_id', ''), _negated=True)), fields=('match', 'sender', 'client_message_id'), name='unique_message_client_id_per_sender'),
        ),
    ]
