# Generated by Django 5.0.14 on 2026-08-03 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['receiver', 'status'], name='match_receiver_status_idx'),
        ),
    ]
