# Generated by Django 5.0.14 on 2026-07-16 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('faith_declaration_accepted', models.BooleanField(default=False)),
                ('selfie_verified', models.BooleanField(default=False)),
                ('doc_url', models.URLField(blank=True, null=True)),
                ('visit_status', models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending'), ('done', 'Done')], default='not_requested', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verifications',
            },
        ),
    ]
