# Generated by Django 5.0.14 on 2026-07-16 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('matchmaker_assisted', 'Matchmaker Assisted')], default='free', max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
