# Generated by Django 5.0.14 on 2026-07-16 15:04

import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('privacy_level', models.CharField(blank=True, choices=[('visible', 'Always Visible'), ('blur_till_match', 'Blurred Until Match'), ('always_blur', 'Always Blurred')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'photos',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interested_in', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age_range_min', models.PositiveSmallIntegerField(default=18)),
                ('age_range_max', models.PositiveSmallIntegerField(default=60)),
                ('city_pref', models.CharField(blank=True, max_length=100, null=True)),
                ('education_pref', models.CharField(blank=True, max_length=150, null=True)),
                ('sect_pref', models.CharField(blank=True, choices=[('sunni', 'Sunni'), ('shia', 'Shia'), ('deobandi', 'Deobandi'), ('barelvi', 'Barelvi'), ('salafi', 'Salafi/Ahle Hadith')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'preferences',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('dob', models.DateField(validators=[core.validators.validate_adult_dob])),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('sect_maslak', models.CharField(choices=[('sunni', 'Sunni'), ('shia', 'Shia'), ('deobandi', 'Deobandi'), ('barelvi', 'Barelvi'), ('salafi', 'Salafi/Ahle Hadith')], max_length=20)),
                ('education', models.CharField(max_length=150)),
                ('marital_status', models.CharField(choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('is_muslim_confirmed', models.BooleanField(default=False)),
                ('photo_privacy_level', models.CharField(choices=[('visible', 'Always Visible'), ('blur_till_match', 'Blurred Until Match'), ('always_blur', 'Always Blurred')], default='blur_till_match', max_length=20)),
                ('profession', models.CharField(blank=True, max_length=150, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_children', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prayer_level', models.CharField(blank=True, max_length=50, null=True)),
                ('hijab_beard_pref', models.CharField(blank=True, max_length=50, null=True)),
                ('smoking_pref', models.CharField(blank=True, max_length=20, null=True)),
                ('drinking_pref', models.CharField(blank=True, max_length=20, null=True)),
                ('halal_meat_pref', models.BooleanField(default=True)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('marriage_intentions', models.CharField(blank=True, max_length=255, null=True)),
                ('wali_chaperone_required', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
