# Generated by Django 5.0.14 on 2026-08-03 06:56

import core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('dob', models.DateField(validators=[core.validators.validate_adult_dob])),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('sect_maslak', models.CharField(choices=[('sunni', 'Sunni'), ('shia', 'Shia'), ('deobandi', 'Deobandi'), ('barelvi', 'Barelvi'), ('salafi', 'Salafi/Ahle Hadith')], max_length=20)),
                ('education', models.CharField(max_length=150)),
                ('marital_status', models.CharField(choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('is_muslim_confirmed', models.BooleanField(default=False)),
                ('photo_privacy_level', models.CharField(choices=[('visible', 'Always Visible'), ('blur_till_match', 'Blurred Until Match'), ('always_blur', 'Always Blurred')], default='blur_till_match', max_length=20)),
                ('profession', models.CharField(blank=True, max_length=150, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_children', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prayer_level', models.CharField(blank=True, max_length=50, null=True)),
                ('hijab_beard_pref', models.CharField(blank=True, max_length=50, null=True)),
                ('smoking_pref', models.CharField(blank=True, max_length=20, null=True)),
                ('drinking_pref', models.CharField(blank=True, max_length=20, null=True)),
                ('halal_meat_pref', models.BooleanField(default=True)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('marriage_intentions', models.CharField(blank=True, max_length=255, null=True)),
                ('wali_chaperone_required', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('privacy_level', models.CharField(blank=True, choices=[('visible', 'Always Visible'), ('blur_till_match', 'Blurred Until Match'), ('always_blur', 'Always Blurred')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profile')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interested_in', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age_range_min', models.PositiveSmallIntegerField(default=18)),
                ('age_range_max', models.PositiveSmallIntegerField(default=60)),
                ('city_pref', models.CharField(blank=True, max_length=100, null=True)),
                ('education_pref', models.CharField(blank=True, max_length=150, null=True)),
                ('sect_pref', models.CharField(blank=True, choices=[('sunni', 'Sunni'), ('shia', 'Shia'), ('deobandi', 'Deobandi'), ('barelvi', 'Barelvi'), ('salafi', 'Salafi/Ahle Hadith')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preferences',
                'indexes': [models.Index(fields=['interested_in'], name='pref_interested_in_idx'), models.Index(django.db.models.functions.text.Lower('city_pref'), name='pref_city_lower_idx'), models.Index(django.db.models.functions.text.Lower('education_pref'), name='pref_education_lower_idx'), models.Index(fields=['sect_pref'], name='pref_sect_pref_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted', 'gender', 'is_muslim_confirmed'], name='profile_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['dob'], name='profile_dob_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['updated_at'], name='profile_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(django.db.models.functions.text.Lower('city'), name='profile_city_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(django.db.models.functions.text.Lower('education'), name='profile_education_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['sect_maslak'], name='profile_sect_maslak_idx'),
        ),
    ]
