# Generated by Django 5.0.14 on 2026-08-09 15:38

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/%Y/%m/%d/', validators=[core.validators.validate_profile_photo]),
        ),
        migrations.AlterField(
            model_name='preference',
            name='sect_pref',
            field=models.CharField(blank=True, choices=[('sunni', 'Sunni'), ('shia', 'Shia'), ('deobandi', 'Deobandi'), ('barelvi', 'Barelvi'), ('salafi', 'Salafi'), ('ahle_hadith', 'Ahle Hadith')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sect_maslak',
            field=models.CharField(choices=[('sunni', 'Sunni'), ('shia', 'Shia'), ('deobandi', 'Deobandi'), ('barelvi', 'Barelvi'), ('salafi', 'Salafi'), ('ahle_hadith', 'Ahle Hadith')], max_length=20),
        ),
    ]
