# Generated by Django 6.1 on 2026-08-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_photo_file_alter_preference_sect_pref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_primary',
        ),
    ]
