# Generated by Django 5.0.14 on 2026-07-23 17:44

import apps.profiles.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_photo_url_photo_image_profile_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=apps.profiles.models.photo_upload_path, validators=[core.validators.validate_image_file]),
        ),
    ]
