# Generated by Django 5.0.14 on 2026-08-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_deleted_at_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'status'], name='user_active_status_idx'),
        ),
    ]
