# Generated by Django 5.0.14 on 2026-08-03 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0003_matchrequest_match_receiver_status_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_photos',
                'ordering': ('display_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='GalleryAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_access_grants', to='matches.matchrequest')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_access_grants', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_access_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gallery_access',
                'indexes': [models.Index(fields=['viewer'], name='gallery_access_viewer_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='galleryaccess',
            constraint=models.UniqueConstraint(fields=('owner', 'match_request'), name='unique_gallery_access_per_owner_match'),
        ),
        migrations.AddConstraint(
            model_name='galleryaccess',
            constraint=models.CheckConstraint(check=models.Q(('owner', models.F('viewer')), _negated=True), name='gallery_owner_and_viewer_differ'),
        ),
    ]
