# Generated by Django 5.0.14 on 2026-08-09 15:38

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalphoto',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gallery_photos/%Y/%m/%d/', validators=[core.validators.validate_profile_photo]),
        ),
    ]
